# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 04:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_name', models.CharField(max_length=100, unique=True)),
                ('hash_value', models.CharField(max_length=2000, unique=True)),
                ('hash_type', models.CharField(max_length=10)),
                ('hash_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Virus_hash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virus_hash_value', models.CharField(max_length=2000, unique=True)),
                ('virus_detail', models.CharField(max_length=3000)),
                ('virus_date', models.DateTimeField(default=datetime.datetime.now)),
                ('virus_file_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Hash')),
            ],
        ),
    ]
